# Generated by Django 2.2.3 on 2019-10-16 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('idNo', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='leaders')),
                ('idNo', models.IntegerField()),
                ('is_leader', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderProjArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor', models.CharField(max_length=255)),
                ('time_archived', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('estimate', models.IntegerField()),
                ('allocation', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaderUpdArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor', models.CharField(max_length=255)),
                ('time_archived', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('day', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MCA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='mcas')),
                ('idNo', models.IntegerField()),
                ('is_mca', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MCAProjArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor', models.CharField(max_length=255)),
                ('time_archived', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('estimate', models.IntegerField()),
                ('allocation', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MCAUpdArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor', models.CharField(max_length=255)),
                ('time_archived', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('day', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='ministry_image')),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='mps')),
                ('idNo', models.IntegerField()),
                ('is_mp', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=255)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kisumu.Constituency')),
            ],
        ),
        migrations.CreateModel(
            name='MPProjArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time_archived', models.DateTimeField(auto_now_add=True)),
                ('estimate', models.IntegerField()),
                ('allocation', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MPUpdArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor', models.CharField(max_length=255)),
                ('time_archived', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('day', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='union_image')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kisumu.Constituency')),
            ],
        ),
        migrations.CreateModel(
            name='UnionUpdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='union_updates')),
                ('location', models.CharField(max_length=255)),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kisumu.Union')),
            ],
        ),
        migrations.CreateModel(
            name='UnionOfficial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('idNo', models.IntegerField()),
                ('is_union_off', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=255)),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kisumu.Union')),
            ],
        ),
        migrations.CreateModel(
            name='MPUpdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='mp_updates')),
                ('location', models.CharField(max_length=255)),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kisumu.MP')),
            ],
        ),
        migrations.CreateModel(
            name='MPProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='mp_projects')),
                ('location', models.CharField(max_length=255)),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('estimate', models.IntegerField()),
                ('allocation', models.IntegerField()),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kisumu.MP')),
            ],
        ),
        migrations.CreateModel(
            name='MinistryUpdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='ministry_updates')),
                ('location', models.CharField(max_length=255)),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kisumu.Ministry')),
            ],
        ),
        migrations.CreateModel(
            name='MinistryProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='ministry_projects')),
                ('location', models.CharField(max_length=255)),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('estimate', models.IntegerField()),
                ('allocation', models.IntegerField()),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kisumu.Ministry')),
            ],
        ),
        migrations.CreateModel(
            name='MinistryOfficial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('idNo', models.IntegerField()),
                ('is_ministry_off', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=255)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kisumu.Ministry')),
            ],
        ),
        migrations.CreateModel(
            name='MCAUpdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='mca_updates')),
                ('location', models.CharField(max_length=255)),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('mca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kisumu.MCA')),
            ],
        ),
        migrations.CreateModel(
            name='MCAProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='mca_projects')),
                ('location', models.CharField(max_length=255)),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('estimate', models.IntegerField()),
                ('allocation', models.IntegerField()),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('mca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kisumu.MCA')),
            ],
        ),
        migrations.AddField(
            model_name='mca',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kisumu.Ward'),
        ),
        migrations.CreateModel(
            name='LeaderUpdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='leader_updates')),
                ('location', models.CharField(max_length=255)),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kisumu.Leader')),
            ],
        ),
        migrations.CreateModel(
            name='LeaderProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='leader_projects')),
                ('location', models.CharField(max_length=255)),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('estimate', models.IntegerField()),
                ('allocation', models.IntegerField()),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kisumu.Leader')),
            ],
        ),
        migrations.AddField(
            model_name='leader',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kisumu.Position'),
        ),
    ]
