from django.contrib import admin
from . import models

admin.site.register(models.Admin)
admin.site.register(models.Constituency)
admin.site.register(models.Ward)
admin.site.register(models.Position)
admin.site.register(models.Leader)
admin.site.register(models.MP)
admin.site.register(models.MCA)
admin.site.register(models.Ministry)
admin.site.register(models.Union)
admin.site.register(models.LeaderProject)
admin.site.register(models.MCAProject)
admin.site.register(models.MPProject)
admin.site.register(models.MinistryProject)
admin.site.register(models.LeaderUpdates)
admin.site.register(models.MCAUpdates)
admin.site.register(models.MPUpdates)
admin.site.register(models.UnionUpdates)
admin.site.register(models.MinistryOfficial)
admin.site.register(models.UnionOfficial)
admin.site.register(models.MPUpdArchive)
admin.site.register(models.LeaderUpdArchive)
admin.site.register(models.MCAUpdArchive)
admin.site.register(models.MPProjArchive)
admin.site.register(models.LeaderProjArchive)
admin.site.register(models.MCAProjArchive)
